package data;

public class Tuple {
	/*
	 * POSITIVE and UPDATE signs are generated by the tagger operator.
	 * A POSITIVE sign is appended to the stream when an object enters the pipeline for the first time.
	 * An UPDATE sign occurs when the object is already in the pipeline but we got a location update for it.
	 * 
	 * For the stream (generated by ConvertSecondo.cs):
	 * All signs are OTHER except for:
	 * NEGATIVE signs which are generated when the object is not mobile for a large period of time.
	 */

	public Tuple() {

	}

	public enum Sign {
		POSITIVE,
		UPDATE,
		NEGATIVE,
		OTHER
	}

	public int movingObjectID;
	public long timeStamp;
	public Sign sign;
	public double xCoord;
	public double yCoord;

	public Tuple(int movingObjectID, long timeStamp, Sign sign, double xCoord, double yCoord) {
		this.movingObjectID = movingObjectID;
		this.timeStamp = timeStamp;
		this.sign = sign;
		this.xCoord = xCoord;
		this.yCoord = yCoord;
	}

	@Override
	public boolean equals(Object obj) {

		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;

		Tuple tuple = (Tuple) obj;
		if (tuple.movingObjectID == this.movingObjectID)
			if (tuple.timeStamp == this.timeStamp)
				return true;
		return false;
	}
}

